//
//  PlanetListViewController.swift
//  Solar System
//
//  Created by Jake Loresch on 11/7/18.
//  Copyright © 2018 Jake Loresch. All rights reserved.
//

import UIKit

class PlanetListViewController: UITableViewController {
    
    
    
    
    
    var planets: [String] = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"]

    override func viewDidLoad() {
        super.viewDidLoad()
    }

    override func numberOfSections(in tableView: UITableView) -> Int {
        // #warning Incomplete implementation, return the number of sections
        return 1
    }

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 8
    }


    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "PlanetCell", for: indexPath)
        print(indexPath)
        let aPlanet = planets[indexPath.row]
        
        cell.textLabel?.text = aPlanet
        //pulls planet name from string list
        cell.imageView?.image = UIImage(named: aPlanet)
        //pulls image of planet based on name of planet generated by previous line
        return cell
    }
    
    override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 50.0
    }
    
    // Override to support conditional editing of the table view.
    override func tableView(_ tableView: UITableView, canEditRowAt indexPath: IndexPath) -> Bool {
        // Return false if you do not want the specified item to be editable.
        return true
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "ToPlanetView" {
            if let destinationViewController = segue.destination as? SinglePlanetViewController {
                if let indexpath = tableView.indexPathForSelectedRow {
                    let planet = planets[indexpath.row]
                    // matches row number to string position in 'planets' array
                    destinationViewController.planet = planet
                    // sets name of planets
                    
                    // let _ = UIImage(named: planet)
                }
            }
        }
    }
}
